import pandas as pd
import os


def combine(project_path=os.getcwd(), primary='data_virginia.xlsx',
            data_files=['data_emerging_tech.xlsx'],
            output='data_combined.xlsx'):
    # ---------------------------------------------------------
    # move to data directory and import data
    # ---------------------------------------------------------
    os.chdir(project_path)
    os.chdir('data')
    df1 = pd.read_excel(primary, sheet_name=None)

    # ---------------------------------------------------------
    # create output file, if already present - delete
    # ---------------------------------------------------------
    about = pd.Series(index=['About', 'Primary input file'], dtype=str)
    about['About'] = 'Data file automatically generated by temoatools'
    about['Primary input file'] = primary
    for i, data_file in enumerate(data_files):
        name = 'Datafile ' + str(i)
        about[name] = data_file
    try:
        os.stat(output)
        os.remove(output)
        with pd.ExcelWriter(output, mode='w') as writer:
            about.to_excel(writer, sheet_name='About', index=True)
    except:
        with pd.ExcelWriter(output, mode='w') as writer:
            about.to_excel(writer, sheet_name='About', index=True)

    # ---------------------------------------------------------
    # process data files
    # ---------------------------------------------------------

    # Iterate through files
    for data_file in data_files:
        df2 = pd.read_excel(data_file, sheet_name=None)

        # Iterate through primary data file keys
        for key in df1.keys():

            # only process sheets that are present in both
            if key in df2.keys():
                a = df1[key]
                b = df2[key]

                # 1st row is to be ignored
                if len(b) > 1:
                    df1[key] = a.append(b[1:], ignore_index=True)

            # write out
            with pd.ExcelWriter(output, mode='a') as writer:
                df1[key].to_excel(writer, sheet_name=key, index=False)

    # return to original directory
    os.chdir('..')
